/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package se.vgregion.delegation.ws;

import javax.jws.WebService;
import javax.persistence.NoResultException;

import se.riv.authorization.delegation.getdelegation.v1.rivtabp21.GetDelegationResponderInterface;
import se.riv.authorization.delegation.getdelegationresponder.v1.GetDelegationResponseType;
import se.riv.authorization.delegation.getdelegationresponder.v1.GetDelegationType;
import se.riv.authorization.delegation.v1.ResultCodeEnum;
import se.vgregion.delegation.DelegationService;
import se.vgregion.delegation.ws.util.DelegationServiceUtil;

/**
 * This class was generated by Apache CXF 2.2.2 Wed Apr 18 14:42:43 CEST 2012 Generated source version: 2.2.2
 * 
 */

@WebService(
        serviceName = "GetDelegationResponderService",
        endpointInterface = "se.riv.authorization.delegation.getdelegation.v1.rivtabp21.GetDelegationResponderInterface",
        portName = "GetDelegationResponderPort",
        targetNamespace = "urn:riv:authorization:delegation:GetDelegation:1:rivtabp21",
        wsdlLocation = "schemas/interactions/GetDelegationInteraction/GetDelegationInteraction_1.0_RIVTABP21.wsdl")
public class GetDelegationResponderInterfaceImpl implements GetDelegationResponderInterface {

    DelegationService delegationService;

    public GetDelegationResponderInterfaceImpl(DelegationService delegationService) {
        super();
        this.delegationService = delegationService;
    }

    @Override
    public GetDelegationResponseType getDelegation(String logicalAddress, GetDelegationType parameters) {

        GetDelegationResponseType delegationResponseType = new GetDelegationResponseType();

        try {
            delegationResponseType.setDelegation(DelegationServiceUtil.convertDelegation(delegationService
                    .findByDelegationKey(Long.parseLong(parameters.getDelegationKey()))));
            delegationResponseType.setResultCode(ResultCodeEnum.OK);
        } catch (NoResultException e) {
            delegationResponseType.setResultCode(ResultCodeEnum.ERROR);
            delegationResponseType.setComment("No delegation found for delegationKey = "
                    + parameters.getDelegationKey());
        }

        return delegationResponseType;

    }

}
