/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package se.vgregion.delegation.ws;

import java.util.logging.Logger;

import javax.jws.WebService;

import se.riv.authorization.delegation.getdelegationsbyunitandrole.v1.rivtabp21.GetDelegationsbyUnitAndRoleResponderInterface;
import se.riv.authorization.delegation.getdelegationsbyunitandroleresponder.v1.GetDelegationsbyUnitAndRoleResponseType;
import se.riv.authorization.delegation.getdelegationsbyunitandroleresponder.v1.GetDelegationsbyUnitAndRoleType;
import se.riv.authorization.delegation.v1.ResultCodeEnum;
import se.vgregion.delegation.DelegationService;
import se.vgregion.delegation.ws.util.DelegationServiceUtil;

/**
 * This class was generated by Apache CXF 2.2.2 Wed Apr 18 14:42:43 CEST 2012 Generated source version: 2.2.2
 * 
 */

@WebService(
        serviceName = "GetDelegationsbyUnitAndRoleResponderService",
        endpointInterface = "se.riv.authorization.delegation.getdelegationsbyunitandrole.v1.rivtabp21.GetDelegationsbyUnitAndRoleResponderInterface",
        portName = "GetDelegationsbyUnitAndRoleResponderPort",
        targetNamespace = "urn:riv:authorization:delegation:GetDelegationsbyUnitAndRole:1:rivtabp21",
        wsdlLocation = "schemas/interactions/GetDelegationsbyUnitAndRoleInteraction/GetDelegationsbyUnitAndRoleInteraction_1.0_RIVTABP21.wsdl")
public class GetDelegationsbyUnitAndRoleResponderInterfaceImpl implements
        GetDelegationsbyUnitAndRoleResponderInterface {

    DelegationService delegationService;

    public GetDelegationsbyUnitAndRoleResponderInterfaceImpl() {
        super();
    }

    public GetDelegationsbyUnitAndRoleResponderInterfaceImpl(DelegationService delegationService) {
        super();
        this.delegationService = delegationService;
    }

    private static final Logger LOG = Logger
            .getLogger(GetDelegationsbyUnitAndRoleResponderInterfaceImpl.class.getName());

    @Override
    public GetDelegationsbyUnitAndRoleResponseType getDelegationsbyUnitAndRole(String logicalAddress,
            GetDelegationsbyUnitAndRoleType parameters) {

        GetDelegationsbyUnitAndRoleResponseType getDelegationsbyUnitAndRoleResponseType =
                new GetDelegationsbyUnitAndRoleResponseType();

        getDelegationsbyUnitAndRoleResponseType.setDelegations(DelegationServiceUtil
                .parseDelegations(delegationService.getDelegationsForToRole(parameters.getDelegatedFor(),
                        parameters.getDelegatedTo(), parameters.getRole())));

        if (getDelegationsbyUnitAndRoleResponseType.getDelegations().getContent().size() > 0) {
            getDelegationsbyUnitAndRoleResponseType.setResultCode(ResultCodeEnum.OK);
        } else {
            getDelegationsbyUnitAndRoleResponseType.setResultCode(ResultCodeEnum.INFO);
            getDelegationsbyUnitAndRoleResponseType
                    .setComment("No delegations found for parameters, delegationFor: "
                            + parameters.getDelegatedFor() + " delegationTo: " + parameters.getDelegatedTo()
                            + " role: " + parameters.getRole());
        }

        return getDelegationsbyUnitAndRoleResponseType;
    }

}
