/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package se.vgregion.delegation.ws;

import java.util.logging.Logger;

import javax.jws.WebService;

import se.riv.authorization.delegation.getdelegations.v1.rivtabp21.GetDelegationsResponderInterface;
import se.riv.authorization.delegation.getdelegationsresponder.v1.GetDelegationsResponseType;
import se.riv.authorization.delegation.getdelegationsresponder.v1.GetDelegationsType;
import se.riv.authorization.delegation.getdelegationsresponder.v1.ResultCodeEnum;
import se.vgregion.delegation.DelegationService;
import se.vgregion.delegation.ws.util.DelegationServiceUtil;

/**
 * This class was generated by Apache CXF 2.2.2 Wed Apr 18 14:42:43 CEST 2012 Generated source version: 2.2.2
 * 
 */

@WebService(
        serviceName = "GetDelegationsResponderService",
        endpointInterface = "se.riv.authorization.delegation.getdelegations.v1.rivtabp21.GetDelegationsResponderInterface",
        portName = "GetDelegationsResponderPort",
        targetNamespace = "urn:riv:authorization:delegation:GetDelegations:1:rivtabp21",
        wsdlLocation = "schemas/interactions/GetDelegationsInteraction/GetDelegationsInteraction_1.0_RIVTABP21.wsdl")
public class GetDelegationsResponderInterfaceImpl implements GetDelegationsResponderInterface {

    DelegationService delegationService;

    public GetDelegationsResponderInterfaceImpl() {
        super();
    }

    public GetDelegationsResponderInterfaceImpl(DelegationService delegationService) {
        super();
        this.delegationService = delegationService;
    }

    private static final Logger LOG = Logger.getLogger(GetDelegationsResponderInterfaceImpl.class.getName());

    @Override
    public GetDelegationsResponseType getDelegations(String logicalAddress, GetDelegationsType parameters) {
        GetDelegationsResponseType gdrt = new GetDelegationsResponseType();

        gdrt.setDelegations(DelegationServiceUtil.parseDelegations(delegationService
                .getDelegations(parameters.getDelegationFor())));

        if (gdrt.getDelegations().getContent().size() > 0) {
            gdrt.setResultCode(ResultCodeEnum.OK);
        } else {
            gdrt.setResultCode(ResultCodeEnum.INFO);
            gdrt.setComment("No delegations found for this delegationFor: " + parameters.getDelegationFor());
        }

        return gdrt;
    }

}
