/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package se.vgregion.delegation.ws;

import java.util.HashMap;
import java.util.logging.Logger;

import javax.jws.WebService;

import org.apache.commons.collections.BeanMap;

import se.riv.authorization.delegation.savedelegations.v1.rivtabp21.SaveDelegationsResponderInterface;
import se.riv.authorization.delegation.savedelegationsresponder.v1.Delegations;
import se.vgregion.delegation.DelegationService;
import se.vgregion.delegation.domain.Delegation;
import se.vgregion.delegation.domain.DelegationBlock;

/**
 * This class was generated by Apache CXF 2.2.2 Wed Apr 18 14:42:43 CEST 2012 Generated source version: 2.2.2
 * 
 */

@WebService(serviceName = "SaveDelegationsResponderService", endpointInterface = "se.riv.authorization.delegation.savedelegations.v1.rivtabp21.SaveDelegationsResponderInterface", portName = "SaveDelegationsResponderPort", targetNamespace = "urn:riv:authorization:delegation:SaveDelegations:1:rivtabp21", wsdlLocation = "file:/C:/Projects/Portal/oppna-program-icc/service-descriptions/authorization-delegation-schemas/trunk/src/main/resources/schemas/interactions/SaveDelegationsInteraction/SaveDelegationsInteraction_1.0_RIVTABP21.wsdl")
public class SaveDelegationsResponderInterfaceImpl implements SaveDelegationsResponderInterface {

    DelegationService delegationService;

    public SaveDelegationsResponderInterfaceImpl() {
        super();
    }

    public SaveDelegationsResponderInterfaceImpl(DelegationService delegationService) {
        super();
        this.delegationService = delegationService;
    }

    private static final Logger LOG = Logger.getLogger(SaveDelegationsResponderInterfaceImpl.class.getName());

    /* public SaveDelegationsResponseType saveDelegations(String logicalAddress, DelegationBlock parameters) { //
     * TODO Auto-generated method stub return null; } */

    @Override
    public Delegations saveDelegations(String logicalAddress,
            se.riv.authorization.delegation.savedelegationsresponder.v1.DelegationBlock delegationBlock) {

        System.out.println("logicalAddress: \n" + logicalAddress + "\n\n");

        DelegationBlock myDelegationBlock = DelegationBlock.toDelegationBlock(delegationBlock);

        BeanMap bm = new BeanMap(myDelegationBlock);
        System.out.println(new HashMap(bm));

        // Save, convert the result and return it.
        Delegations result = new Delegations();
        result.getContent().addAll(
                Delegation.convert(delegationService.save(myDelegationBlock).getDelegations(),
                        se.riv.authorization.delegation.savedelegationsresponder.v1.Delegation.class));

        return result;
    }

}
